//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogin
    {
        public int CodLogin { get; set; }
        public Nullable<int> CodAccount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual TblAccount TblAccount { get; set; }
    }
}
