CREATE DATABASE ACADEMYSOLUTIONS;
GO

USE ACADEMYSOLUTIONS;

CREATE TABLE TblAccount(
	CodAccount INT IDENTITY(1,1000),
	NameFull VARCHAR(25) NOT NULL,
	DateBirth DATETIME,
	DateRegister DATETIME,
	CodCategory INT
)

CREATE TABLE TblLogin(
	CodAccount INT,
	Username VARCHAR(20),
	Password VARCHAR (40)
)

CREATE TABLE TblCategory(
	CodCategory INT,
	Name VARCHAR(20),
	Description TEXT
)

CREATE TABLE TblList(
	CodList INT,

)

ALTER TABLE TblAccount ADD
	CONSTRAINT PK_ACCOUNT 
		PRIMARY KEY (CodAccount);

ALTER TABLE TblLogin ADD
	CONSTRAINT FK_LOGIN_PK_ACCOUNT 
		FOREIGN KEY (CodAccount) REFERENCES TblAccount (CodAccount);